# Generated by Django 4.2.1 on 2023-06-14 11:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_spendingrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spendingrecord',
            name='time_stamp',
            field=models.DateField(default=datetime.datetime(2023, 6, 14, 19, 44, 41, 337543)),
        ),
    ]
