# Generated by Django 4.2.1 on 2023-06-19 12:37

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0006_spendingrecord_currency'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='spendingrecord',
            managers=[
                ('custom_query', django.db.models.manager.Manager()),
            ],
        ),
    ]
