# Generated by Django 4.2.1 on 2023-05-30 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0001_initial'),
        ('financial_accounts', '0003_savingsaccount_currency_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savingsaccount',
            name='currency_code',
        ),
        migrations.AddField(
            model_name='savingsaccount',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='currencies.currency'),
        ),
    ]
