# Generated by Django 4.2.1 on 2023-06-27 04:40

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='deposit',
            managers=[
                ('custom_query', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='withdrawal',
            managers=[
                ('custom_query', django.db.models.manager.Manager()),
            ],
        ),
    ]
